# Based partially on Alyxia's work, thanks so much!

name: Release
on:
  push:
    tags:
      - v*

permissions:
  contents: read

env:
  FORCE_COLOR: true

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install Go dependencies
        run: go get -v

      - name: Build Cli
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -trimpath -tags "static cli" -ldflags "-s -w -X 'plexcordinstaller/buildinfo.InstallerGitHash=$(git rev-parse --short HEAD)' -X 'plexcordinstaller/buildinfo.InstallerTag=${{ github.ref_name }}'" -o PlexcordInstallerCli-linux

      - name: Update executable
        run: |
          chmod +x PlexcordInstallerCli-linux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PlexcordInstaller-linux
          path: |
            PlexcordInstallerCli-linux


  build-mac:
    runs-on: macos-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - id: go-cache-paths
        run: |
          echo "go_build=$(go env GOCACHE)" >> $GITHUB_ENV
          echo "go_mod=$(go env GOMODCACHE)" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: brew install pkg-config sdl2

      - name: Install Go dependencies
        run: go get -v

      - name: Build
        run: CGO_ENABLED=1 GOOS=darwin GOARCH=amd64 go build -v -tags static -ldflags "-s -w -X 'plexcordinstaller/buildinfo.InstallerGitHash=$(git rev-parse --short HEAD)' -X 'plexcordinstaller/buildinfo.InstallerTag=${{ github.ref_name }}'" -o PlexcordInstaller

      - name: Update executable
        run: |
          chmod +x PlexcordInstaller

      - name: Generate MacOS bundle
        run: |
          mkdir -p PlexcordInstaller.app/Contents/MacOS
          mkdir -p PlexcordInstaller.app/Contents/Resources
          cp macos/Info.plist PlexcordInstaller.app/Contents/Info.plist
          mv PlexcordInstaller PlexcordInstaller.app/Contents/MacOS/PlexcordInstaller
          cp macos/icon.icns PlexcordInstaller.app/Contents/Resources/icon.icns
          zip -r PlexcordInstaller.MacOS.zip PlexcordInstaller.app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PlexcordInstaller-macos
          path: PlexcordInstaller.MacOS.zip


  build-windows:
    runs-on: windows-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~\AppData\Local\go-build
            ~\go\pkg\mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2

      - name: Install Windows dependencies
        shell: msys2 {0}
        run: |
          pacman -S --noconfirm git mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2 mingw-w64-x86_64-go
          export GOROOT=/mingw64/lib/go
          export GOPATH=/mingw64

      - name: Install Go dependencies
        shell: msys2 {0}
        run: |
          export GOROOT=/mingw64/lib/go
          export GOPATH=/mingw64
          go get -v
          go install github.com/tc-hib/go-winres@latest

      - name: Build Gui
        shell: msys2 {0}
        run: |
          export GOROOT=/mingw64/lib/go
          export GOPATH=/mingw64
          go-winres make --product-version "git-tag"
          CGO_ENABLED=1 GOOS=windows GOARCH=amd64 go build -v -tags static -ldflags "-s -w -H=windowsgui -extldflags=-static -X 'plexcordinstaller/buildinfo.InstallerGitHash=$(git rev-parse --short HEAD)' -X 'plexcordinstaller/buildinfo.InstallerTag=${{ github.ref_name }}'" -o PlexcordInstaller.exe

      - name: Build i386 Cli
        shell: msys2 {0}
        run: |
          export GOROOT=/mingw64/lib/go
          export GOPATH=/mingw64
          CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -v -trimpath -tags "static cli" -ldflags "-s -w -extldflags=-static -X 'plexcordinstaller/buildinfo.InstallerGitHash=$(git rev-parse --short HEAD)' -X 'plexcordinstaller/buildinfo.InstallerTag=${{ github.ref_name }}'" -o PlexcordInstallerCli.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: PlexcordInstaller-windows
          path: |
            PlexcordInstaller.exe
            PlexcordInstallerCli.exe


  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-mac, build-windows]
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v4
        with:
          name: PlexcordInstaller-linux
          path: linux

      - uses: actions/download-artifact@v4
        with:
          name: PlexcordInstaller-macos
          path: macos

      - uses: actions/download-artifact@v4
        with:
          name: PlexcordInstaller-windows
          path: windows

      - name: Create the release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5 # v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          name: ${{ github.ref_name }}
          prerelease: false
          draft: false
          files: |
            linux/PlexcordInstallerCli-linux
            macos/PlexcordInstaller.MacOS.zip
            windows/PlexcordInstalle*.exe
